### ISSUE TITLE
Make deploy script configurable

### ISSUE THREAD

**Issue by kargakis** [regen-network/toucan-bridge#11]
Address the TODOs in https://github.com/regen-network/toucan-bridge/blob/61eb1e24d07d4248760bb62077187c325e03997b/scripts/toucan-bridge.js

**Comment by kargakis** [comment]
@pheuberger something you may want to have a look at?

**Comment by kargakis** [comment]
Regarding singers, we should be able to use our own private key or mnemonic found in env variables (have a look at how we do this in tokenizer). Same for the rest of the configurables, we should be able to provide them via env variables.

**Comment by pheuberger** [comment]
got it! do you also want to configure the addresses via env vars?

**Comment by kargakis** [comment]
Yes, sorry for not being clear, that's what I meant with "the rest of configurables"
https://github.com/regen-network/toucan-bridge/blob/b41af95ad0c1d93e561b2d907dae56f6961694dd/scripts/toucan-bridge.js#L8-L10

**Comment by pheuberger** [comment]
perfect, thanks for clearing that up :) I'll create a task
