### ISSUE TITLE
Enforce precision in bridge function

### ISSUE THREAD

**Issue by dave** [regen-network/toucan-bridge#21]
Re: https://github.com/rnd-inc/toucan-bridge-service/issues/69#issuecomment-1180577061

If we try to send an amount to regen with more than 6 decimal places - e.g. 1.0000005, then the bridge process will fail. This is very bad because the tokens will be burnt and we will have to manually fix it. 

A better solution would be to immediately fail before the tokens are burnt (in the bridge contract).

Needs another check here I think: https://github.com/regen-network/toucan-bridge/blob/e6be89331a6150385ef73533f349f09183e95980/contracts/ToucanRegenBridge.sol#L89

@pheuberger

**Comment by kargakis** [comment]
Divide then multiply the amount by 10^12 and if the resulting number is the same as the original amount, then it's valid (no decimals lower than 6 have been used).

**Comment by kargakis** [comment]
If 10^12 can be expressed as a power of 2, we could also do shifts which are way cheaper than division and multiplication.

**Comment by dave** [comment]
I think @pheuberger was it a bit worried about putting regen-specific logic in this contract... Perhaps this needs to be configurable?

**Comment by kargakis** [comment]
The contract already has Regen-specific logic (eg., [here](https://github.com/regen-network/toucan-bridge/blob/8b5238d9aa6c4a7682bcb732138f1cbdd14f04e4/contracts/ToucanRegenBridge.sol#L42)) and the [name](https://github.com/regen-network/toucan-bridge/blob/8b5238d9aa6c4a7682bcb732138f1cbdd14f04e4/contracts/ToucanRegenBridge.sol#L16) is also Regen-centric.

**Comment by dave** [comment]
OK cool, sounds like we can put this logic in the contract then 👍

**Comment by pheuberger** [comment]
> I think @pheuberger was it a bit worried about putting regen-specific logic in this contract... Perhaps this needs to be configurable?

i was heading out when you brought it up and didn’t realize this was the toucan-regen bridge contract, so i take it all back 😁

**Comment by pheuberger** [comment]
feature is implemented in #29.
