### ISSUE TITLE
Only allow bridging of NCT eligible tokens

### ISSUE THREAD

**Issue by pheuberger** [regen-network/toucan-bridge#23]
We want to limit the type of credits being bridged to Regen to only NCT eligible tokens. The bridge function needs to check for the necessary attributes and revert if NCT criteria aren't met.

**Comment by dave** [comment]
Yes I just added a test case to the end-to-end tests. The bridge should fail when a non-NCT asset is bridges, but it succeeds:

https://github.com/rnd-inc/toucan-bridge-service/pull/90/commits/606c47a7c5f9766fd3fa519a62ddeec41f0f94c7

(Methodology = VM0022)

**Comment by kargakis** [comment]
Fixed by https://github.com/regen-network/toucan-bridge/pull/25
