### ISSUE TITLE
Deploy new set of contracts to Mumbai

### ISSUE THREAD

**Issue by dave** [regen-network/toucan-bridge#42]
At the last weekly meeting we had a good chat about the pros and cons of running the end-to-end tests in the staging Mumbai / Redwood testnet environment. The tests create new Toucan projects, vintages and batches (with a random string appended to the name). This is the only way we can test the functionality of the bridge when a new project that has never been bridged from is used.

We decided not to spam the main Toucan contracts on Mumbai with this data, but it was decided that we can deploy a new set of Toucan contracts to Mumbai, and set up a new credit class in the Regen Redwood environment.

This ticket is for deploying the contracts to Mumbai.

As mentioned in https://github.com/rnd-inc/toucan-bridge-service/issues/190 I'll need:

* Contract addresses for CarbonProjects, CarbonProjectVintages, CarbonOffsetBatches, ToucanCarbonOffsetsFactory, NatureCarbonTonne, ToucanRegenBridge
* Permissions added to the admin account `0x58f0fA4D76f28E3f5F182acD9c052359cAF3a60D` (so it can create projects, etc).
* Permissions added to the bridge account `0xd04C5Fa5E6E086cc7Dbf2e4495b9E3dCF6A70FC0` (so it can run the bridge).

Related to https://github.com/rnd-inc/toucan-bridge-service/pull/191 and https://github.com/rnd-inc/toucan-bridge-service/issues/195

**Comment by dave** [comment]
How are the current contracts deployed to Mumbai? Is it automated? If so, it would be great to have these new contracts refreshed whenever the others are deployed.

**Comment by aspiers** [comment]
New contracts were just deployed by @marceljay:

https://github.com/rnd-inc/toucan-bridge-service/issues/199#issuecomment-1247054329

**Comment by dave** [comment]
@marceljay this doesn't seem to include the bridge contract... Does that need to be deployed separately?

**Comment by pheuberger** [comment]
Bridge contract deployed under: `0x6e92b8D626309E12918407Ee88601d90DB1ee138`, with token issuer addres `0x11241e35B3f79099123aA0C1C4c97b1FcdCd21f6`

**Comment by aspiers** [comment]
Can this be closed now, or is something else needed?

**Comment by pheuberger** [comment]
yes, closing it now
