### ISSUE TITLE
Correct roles in e2e staging environment

### ISSUE THREAD

**Issue by dave** [regen-network/toucan-bridge#45]
@pheuberger @kargakis @marceljay

It looks like we got the accounts mixed up when adding the roles:

admin (will be used to add projects, vintages etc):
```
0x58f0fA4D76f28E3f5F182acD9c052359cAF3a60D
```

bridge (will run the bridge.):
```
0xd04C5Fa5E6E086cc7Dbf2e4495b9E3dCF6A70FC0
```

From the looks of it, we didn't add the manager role to 0x58... (right now, addProject fails with `Caller is not authorized`)

**Comment by dave** [comment]
... and when I authenticate with the bridge account (which has the manager role), I get "Ownable: caller is not the owner" from addAttributes ... I guess that's from the NatureCarbonTonne contract... Do I need a separate role to call that? Here's the failing transaction:

https://mumbai.polygonscan.com/tx/0xd39ce4362dad4b805b3f6ab3326072a86c1917a6889ab4ef454d65bac5cc164e

**Comment by pheuberger** [comment]
closing this. @dave got everything working yesterday

**Comment by dave** [comment]
No, this wasn't fixed... We got the other issue solved, but the roles never got sorted.

**Comment by dave** [comment]
After discussion we decided that some of the advanced things that the e2e tests do can only be performed by the owner account, so I'm using that as the admin address in the tests: `0x702455C6C1B94Af4FfeC5352303ad496d2c61CcA`
