### ISSUE TITLE
Team Omega Code Review

### ISSUE THREAD

**Issue by jellegerbrandy** [regen-network/toucan-bridge#54]
1. The README says the contract is a one way bridge, but the contract allows for 2 way bridging, the README should be updated.
1. Consider to replace `require` statements with custom errors.
1. No event parameters are currently indexed. It is recommended to index event parameters which might be interesting to filter events by (like sender and recipient addresses).
1. The `totalTransferred` counter is not decreased when tokens are bridged back from Regen to Polygon, is that intentional?
1.  In `issueTCO2Tokens`, the bridge will not accept to mint more tokens on the polygon network then were sent from the Regen bridge in the first place. This only makes sense if this bridge is the only way to create tco2 tokens on regen. Is that the case?
1. In the constructor, the `tokenIssuer` automatically gets the `PAUSER_ROLE`, but on `setTokenIssuer` there is no change to the user role (neither taken from the previous tokenIssuer not given to the new tokenIssuer), is that as intended?
1. In the regen block explorer there are addresses with 44 or 51 characters, but the code checks for 44 or 64 characters. I didn't find documentation about the regen address format. Is this correct?  
1. In package.json, a floating versions of openzeppelin is used: `@openzeppelin/contracts": "^4.6.0",`. It is better to define a fixed version here so that it is unambiguous which version of the contracts is compiled in.	
1. to apply the GPL, you must also claim the copyright (as the LICENSE file explains):
```         How to Apply These Terms to Your New Programs

  If you develop a new program, and you want it to be of the greatest
possible use to the public, the best way to achieve this is to make it
free software which everyone can redistribute and change under these terms.

  To do so, attach the following notices to the program.  It is safest
to attach them to the start of each source file to most effectively
state the exclusion of warranty; and each file should have at least
the "copyright" line and a pointer to where the full notice is found.

    <one line to give the program's name and a brief idea of what it does.>
    Copyright (C) <year>  <name of author>

....
  ```
10. You can save a little gas here bc you already checked the first 6 chars by replacing `for (uint64 i = 0; i < accountLen; i++) {` with   `for (uint64 i = 6; i < accountLen; i++) {`       
1. solidity version 0.8.4 (As defined in hardhat.config) is almost a year old - the latest version if 0.8.17
1. Access management overly complicated. It mixes different approaches: `AccessControl` to define who can pause the contracts, it uses `Ownable`  to limit who can set the pause and define the token issuer, and it defines a state variable `tokenIssuer` to limit access to the `issueTCO2Tokens` function. We'd recommend to land on a single It is probably easier to use the roles from AccessControl to do all access management in a consistent way. This means to get rid of the Ownable inheritance and the tokenIssuer management functions, and to remove grantPauserRole and revokePauserRole, and instead assign the DEFAULT_ADMIN_ROLE to the deployer in the constructor ` _setupRole(DEFAULT_ADMIN_ROLE, msg.sender);` and add a  `TOKEN_ISSUER_ROLE` 
1. We are not clear about the purpose of storing and checking the uniqueness of `origin` in `issueTCO2Tokens` - is there a specific reason to store this string?

**Comment by aspiers** [comment]
Quick initial reactions:

1. Agreed.
2. Yes agreed, @0xmichalis is this doable within (say) <= 60 mins?
3. Great catch, that definitely sounds like something we should fix.
4. Sounds like an omission but we'll check.
5. Sounds like maybe a bug but we'll check.
6. Doesn't sound ideal to me.  Either way we should have events for every role change so that we can track via subgraph.
7. Will defer to @ryanchristo on this one.
8. Good point, @0xmichalis are you OK with this proposed change?
9. Yep, important given this is a public repo.

@0xmichalis is probably better placed to respond to the remaining points 10--13.  If any warrant more lengthy discussion then I suggest splitting off into separate GitHub issues, although it's also fine by me if we don't do that.

**Comment by 0xmichalis** [comment]
`2.` AFAIK Polygonscan does not support custom errors yet, that's the only reason we haven't switched to use custom errors in other Toucan contracts. I guess there is an argument to be made about switching here since this contract is not going to be upgradeable but its size is small and the functions are not gas-intensive so not sure there is a big advantage to switching.
`4.` Hrm, unclear, it seems that initially [`totalTransferred`](https://github.com/regen-network/toucan-bridge/blob/f69de4fe013f0024c13ca3e6acebac3b2d7f471f/contracts/ToucanRegenBridge.sol#L33) was meant to track burnt supply? I feel we should probably update it to track supply that exists in Regen (hence subtract on mints).
`5.` Yes, intentional, this is going to be the only contract sitting between Toucan and Regen to my understanding.
`8.` Yes, in favor of pinning the version. 
`10-12.` in favor of these changes
`13.` AFAIK it's a feature that helps the backend that listens to burn events to deduplicate requests in Regen

The rest of the points also make sense to me. 👍🏼

**Comment by ben-kaufman** [comment]
About 4, if you don't really need the `totalTransferred` on-chain, you could save some gas by removing it, and calculating off chain its value using the events the contract emits (the events emit the `amount` which can be summed up for the total).

**Comment by ben-kaufman** [comment]
> 6. Doesn't sound ideal to me.  Either way we should have events for every role change so that we can track via subgraph.

Note that the `_grantRole` call does emit a `RoleGranted` event already which the subgraph can index. It's more of a question about the consistency of how this logic works.

**Comment by 0xmichalis** [comment]
> About 4, if you don't really need the totalTransferred on-chain, you could save some gas by removing it, and calculating off chain its value using the events the contract emits (the events emit the amount which can be summed up for the total).

I am also fine with removing completely and just piggybacking on the events. 👍🏼 @aspiers we will need to build Subgraph mappings for this contract anyway to keep track of roles.

**Comment by ryanchristo** [comment]
> In the regen block explorer there are addresses with 44 or 51 characters, but the code checks for 44 or 64 characters. I didn't find documentation about the regen address format. Is this correct?

A standard account address is 44 characters long (prefixed with `regen1`). Addresses with 51 characters are either validator addresses or consensus node addresses (prefixed with `regenvaloper1` and `regenvalcons1` respectively), which are not valid addresses to send credits to (i.e. they are used specifically for network validation and consensus).

Group account addresses are derived addresses, meaning they are derived from another address, and in this case they are derived from the address of the group module. Group account addresses are 64 characters long and valid addresses to send credits to. We don't have any group accounts on mainnet yet.

You can view an example of a group account address on our test network here:
- http://redwood.regen.network:1317/cosmos/group/v1/group_policies_by_group/1

We should have documentation for this. Some documentation exists on the cosmos sdk site:
- https://docs.cosmos.network/v0.46/basics/accounts.html
- https://docs.cosmos.network/v0.46/modules/group/

**Comment by nora-rothman** [comment]
> 
> Group account addresses are derived addresses, meaning they are derived from another address, and in this case they are derived from the address of the group module. Group account addresses are 64 characters long and valid addresses to send credits to. We don't have any group accounts on mainnet yet.
>

Based on this response, it seems to me that we do NOT need to address 7.

**Comment by aaronc** [comment]
Technically there can be addresses shorter than 44 characters and longer than 64 characters, although they are unlikely to exist in the near term. I would be less stringent with this check to future proof things. The more important check is for the regen address prefix

**Comment by nora-rothman** [comment]
> 

Thanks @aaronc ! "Less stringent" -- what specifically do you recommend instead of what we have?

**Comment by aaronc** [comment]
I would recommend checking that the prefix is always `regent` and that the length doesn't exceed something like 256 characters. Does that seem reasonable @ryanchristo ?

**Comment by ryanchristo** [comment]
I proposed and implemented the current restrictions https://github.com/regen-network/toucan-bridge/issues/48 and think the more specific the better to prevent user error and burned tokens with no credits created on regen (which we could resolve manually but more operational costs). I was not aware that there were plans to support shorter and longer addresses in cosmos sdk.

**Comment by ryanchristo** [comment]
I would vote to keep the restrictions as is but not entirely opposed to making them less strict and more future proof. I don't know how soon we will see different address lengths, but if not within the next year, I think we should leave as is.

**Comment by nora-rothman** [comment]
Would be great to minimize work as the team is overloaded, so let's please
leave as-is per Ryan's advice. Thanks, all!

**Comment by aaronc** [comment]
That's fine as long as they work for group addresses
